# Generated by Django 2.2 on 2020-08-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['update_date', 'pk']},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='kakao_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
