# Generated by Django 2.2 on 2020-07-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20200706_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='comment_page_number',
            new_name='comment_count',
        ),
    ]
